#!/usr/bin/python3

import sys


def password_check(input_file):
    with open('checked_files', 'a+') as check_file:
        check_file.seek(0, 0)
        reading = check_file.readlines()
        for line in reading:
            find = False
            if input_file in line:
                print('File with current named checked, please check filename.')
                while True:
                    yes_no = input('Do you want to continue? (y/n): ')
                    if yes_no == 'n':
                        sys.exit()
                    elif yes_no == 'y':
                        check_file.write(input_file + '\n')
                        find = True
                        break
            if find:
                break
    # Open 3 files, input_file to reading, and 2 files to reading and writing
    with open(input_file, 'r') as infile, open('eg-all-passwords.dic', 'a+') as outfile, \
            open('eg-all-passwords-wpa2.dic', 'a+') as outfile_wpa:
        # Reading one string in input_file:
        for line_in in infile:
            number_repeated_pass = 0
            outfile.seek(0, 0)
            for line_out in outfile:
                if line_in in line_out:
                    number_repeated_pass += 1
            if number_repeated_pass == 0:
                outfile.write(line_in)
                if len(line_in) > 8:
                    outfile_wpa.write(line_in)

    print('Done!')

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print('Usage: password_checker [input_filename]')
        print()
        print('Try -h or --help for more help.')
        sys.exit()

    elif len(sys.argv) < 2:
        if sys.argv[1] == '-h' or sys.argv[1] == '--help':
            print('Usage: password_checker [input filename]')
            print()
            print('[input filenamge] -- enter dir and filename')
            print('')
        else:
            print('Usage: password_checker [input_filename]')
            print()
            print('Try -h or --help for more help.')

    else:
        password_check(sys.argv[1])